.TH "Hangman.Naziv" 3 "Thu Jan 14 2016" "Version 1.0" "hangman-service" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hangman.Naziv \- 
.SH SYNOPSIS
.br
.PP
.SS "Javni članovi"

.in +1c
.ti -1c
.RI "\fBNaziv\fP (int?id, String title)"
.br
.in -1c
.SS "Osobine"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get]\fP"
.br
.ti -1c
.RI "String \fBTitle\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Opširniji opis"
.PP 
\fBNaziv\fP <br> Klasa predstavlja jedan red iz tabele naziv 
.SH "Dokumentacija konstruktora i destruktora"
.PP 
.SS "Hangman\&.Naziv\&.Naziv (int? id, String title)\fC [inline]\fP"
Prima dva ardumenta <br> id - id naziva iz baze ili NULL <br> title - naziv filma 
.SH "Dokumentacija osobina"
.PP 
.SS "int Hangman\&.Naziv\&.Id\fC [get]\fP"
Polje Id <br> nalazi se u bazi podataka <br> omoguceno je samo citanje 
.SS "String Hangman\&.Naziv\&.Title\fC [get]\fP, \fC [set]\fP"
Polje Title <br> sadrzi naziv filma <br> omoguceno je citanje i pisanje 

.SH "Autor"
.PP 
Napravljeno automatski korišćenjem alata Doxygen za projekat hangman-service od izvornog koda\&.
