.TH "Hangman" 3 "Sun Apr 3 2016" "Version 1.0" "hangman-service" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hangman \- 
.SH SYNOPSIS
.br
.PP
.SS "Klase, strukture i unije"

.in +1c
.ti -1c
.RI "class \fBDataBase\fP"
.br
.ti -1c
.RI "class \fBFilm\fP"
.br
.ti -1c
.RI "class \fBRekord\fP"
.br
.ti -1c
.RI "class \fBServiceFault\fP"
.br
.in -1c
.SH "Autor"
.PP 
Napravljeno automatski korišćenjem alata Doxygen za projekat hangman-service od izvornog koda\&.
