.TH "Hangman.Data" 3 "Thu Jan 14 2016" "Version 1.0" "hangman-service" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hangman.Data \- 
.SH SYNOPSIS
.br
.PP
.PP
Spisak osnovnih klasa: 
.SS "Javni članovi"

.in +1c
.ti -1c
.RI "void \fBOpen\fP ()"
.br
.ti -1c
.RI "List< \fBRekord\fP > \fBPreuzmiRekorde\fP (int?br)"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Zaštićeni članovi"

.in +1c
.ti -1c
.RI "virtual void \fBDispose\fP (bool disposing)"
.br
.in -1c

.SH "Autor"
.PP 
Napravljeno automatski korišćenjem alata Doxygen za projekat hangman-service od izvornog koda\&.
