.TH "HangmanService.IHangmanService" 3 "Sat Apr 30 2016" "Version 1.0" "hangman-service" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HangmanService.IHangmanService \- 
.SH SYNOPSIS
.br
.PP
.PP
Spisak izvedenih klasa: 
.SS "Javni članovi"

.in +1c
.ti -1c
.RI "int[] \fBPokreniIgru\fP ()"
.br
.ti -1c
.RI "List< int > \fBProvera\fP (char[] slovo)"
.br
.ti -1c
.RI "int \fBBrojPokusaja\fP ()"
.br
.ti -1c
.RI "EStatusIgre \fBStatus\fP ()"
.br
.ti -1c
.RI "List< \fBRekord\fP > \fBPreuzmiRekorde\fP (int?br=null)"
.br
.ti -1c
.RI "void \fBSnimiRekord\fP (String ime)"
.br
.in -1c
.SH "Dokumentacija funkcija članica"
.PP 
.SS "int HangmanService\&.IHangmanService\&.BrojPokusaja ()"
Metoda koja vraca broj preostalih zivota 
.PP
Definicija u 
.SS "int [] HangmanService\&.IHangmanService\&.PokreniIgru ()"
Metoda koja pokrece igru 
.br
 sve setuje na nulu i snima trenutno vreme na serveru 
.PP
Definicija u 
.SS "List<\fBRekord\fP> HangmanService\&.IHangmanService\&.PreuzmiRekorde (int? br = \fCnull\fP)"
Metoda vraca listu Rekordas 
.br
prima jedan argument koji predstavlja broj 
.br
rekorda koje treba preuzeti, ako je null (default) vraca sve rekorde 
.PP
Definicija u 
.SS "List<int> HangmanService\&.IHangmanService\&.Provera (char[] slovo)"
Metoda koja proverava da li se zadato slovo nalazi u imenu filma 
.br
 vraca listu indexa na kojima se nalazi slovo, a ako slova nema, praznu listu 
.PP
Definicija u 
.SS "void HangmanService\&.IHangmanService\&.SnimiRekord (String ime)"
Metoda dodaje rekord u bazu 
.br
 ime - ime korisnika koji je resavao sudoku 
.PP
Definicija u 
.SS "EStatusIgre HangmanService\&.IHangmanService\&.Status ()"
Metoda koja vraca status igre
.br
.IP "\(bu" 2
enumeraciju EStatusIgre 
.PP

.PP
Definicija u 

.SH "Autor"
.PP 
Napravljeno automatski korišćenjem alata Doxygen za projekat hangman-service od izvornog koda\&.
