.TH "HangmanService" 3 "Fri May 6 2016" "Version 1.0" "hangman-service" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HangmanService \- 
.SH SYNOPSIS
.br
.PP
.SS "Klase, strukture i unije"

.in +1c
.ti -1c
.RI "class \fBHangmanService\fP"
.br
.ti -1c
.RI "interface \fBIHangmanService\fP"
.br
.ti -1c
.RI "class \fBMainClass\fP"
.br
.in -1c
.SS "Nabrajanja"

.in +1c
.ti -1c
.RI "enum \fBEStatusIgre\fP { \fBIGRA_AKTIVNA\fP, \fBIGRA_ZAVRSENA_POBEDA\fP, \fBIGRA_ZAVRSENA_PORAZ\fP }"
.br
.in -1c
.SH "Autor"
.PP 
Napravljeno automatski korišćenjem alata Doxygen za projekat hangman-service od izvornog koda\&.
