.TH "HangmanService.IHangmanService" 3 "Thu Jan 14 2016" "Version 1.0" "hangman-service" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HangmanService.IHangmanService \- 
.SH SYNOPSIS
.br
.PP
.PP
Spisak izvedenih klasa: 
.SS "Javni članovi"

.in +1c
.ti -1c
.RI "List< \fBRekord\fP > \fBPreuzmiRekorde\fP (int?br)"
.br
.in -1c
.SH "Dokumentacija funkcija članica"
.PP 
.SS "List<\fBRekord\fP> HangmanService\&.IHangmanService\&.PreuzmiRekorde (int? br)"
Metoda vraca listu Rekordas 
.br
prima jedan argument koji predstavlja broj 
.br
rekorda koje treba preuzeti, ako je null 
.br
vraca sve rekorde 
.PP
Definicija u 

.SH "Autor"
.PP 
Napravljeno automatski korišćenjem alata Doxygen za projekat hangman-service od izvornog koda\&.
