.TH "HangmanService.HangmanService" 3 "Sat Apr 30 2016" "Version 1.0" "hangman-service" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HangmanService.HangmanService \- 
.SH SYNOPSIS
.br
.PP
.PP
Spisak osnovnih klasa: 
.SS "Javni članovi"

.in +1c
.ti -1c
.RI "int[] \fBPokreniIgru\fP ()"
.br
.ti -1c
.RI "List< int > \fBProvera\fP (char[] slovo)"
.br
.ti -1c
.RI "int \fBBrojPokusaja\fP ()"
.br
.ti -1c
.RI "EStatusIgre \fBStatus\fP ()"
.br
.ti -1c
.RI "List< \fBRekord\fP > \fBPreuzmiRekorde\fP (int?br=null)"
.br
.ti -1c
.RI "void \fBSnimiRekord\fP (String ime)"
.br
.in -1c
.SH "Dokumentacija funkcija članica"
.PP 
.SS "int HangmanService\&.HangmanService\&.BrojPokusaja ()\fC [inline]\fP"
Metoda koja vraca broj preostalih zivota 
.PP
.SS "int [] HangmanService\&.HangmanService\&.PokreniIgru ()\fC [inline]\fP"
Metoda koja pokrece igru 
.br
 sve setuje na nulu i snima trenutno vreme na serveru 
.PP
.SS "List<\fBRekord\fP> HangmanService\&.HangmanService\&.PreuzmiRekorde (int? br = \fCnull\fP)\fC [inline]\fP"
Metoda vraca listu Rekorda 
.br
 id - broj rekorda za preuzimanje, ako je null vraca sve rekorde, default vrednost je null 
.PP
.SS "List<int> HangmanService\&.HangmanService\&.Provera (char[] slovo)\fC [inline]\fP"
Metoda koja proverava da li se zadato slovo nalazi u imenu filma 
.br
 vraca listu indexa na kojima se nalazi slovo, a ako slova nema, praznu listu 
.PP
.SS "void HangmanService\&.HangmanService\&.SnimiRekord (String ime)\fC [inline]\fP"
Metoda dodaje rekord u bazu 
.br
 ime - ime korisnika koji je resavao sudoku 
.PP
.SS "EStatusIgre HangmanService\&.HangmanService\&.Status ()\fC [inline]\fP"
Metoda koja vraca status igre
.br
.IP "\(bu" 2
enumeraciju EStatusIgre 
.PP

.PP


.SH "Autor"
.PP 
Napravljeno automatski korišćenjem alata Doxygen za projekat hangman-service od izvornog koda\&.
